Feature/set controller layout
soramitsu/fearless-Android pull request #258
Opened 2021-05-04 18:11 UTC by FrogTravel

Basic logic for a controller account screen

2021-05-05 06:59 UTC, valentunn requested changes

2021-05-05 06:59 UTC, valentunn commented on feature-staking-impl/src/main/java/jp/co/soramitsu/feature_staking_impl/presentation/staking/controller/SetControllerViewModel.kt
> +    val showControllerChooserEvent: LiveData<Event<Payload<AddressModel>>> = _showControllerChooserEvent
![image](https://user-images.githubusercontent.com/70131744/117106021-cc04f800-ad87-11eb-8ea5-f5adb1cc2d39.png)
Нужно немного кастомизировать компонент, чтобы была возможность менять  заголовок. Так как нам тут нужен payout account

2021-05-05 06:59 UTC, valentunn commented on feature-staking-impl/src/main/java/jp/co/soramitsu/feature_staking_impl/presentation/staking/controller/SetControllerViewModel.kt
> +    private val _controllerAccountModel = MutableLiveData<AddressModel>()
Нужно инициализировать эту лайвдату текущим контроллером, чтобы не было пустого поля в начале
![image](https://user-images.githubusercontent.com/70131744/117106095-ee971100-ad87-11eb-846a-d4e9c061cad1.png)

2021-05-05 06:59 UTC, valentunn commented on feature-staking-impl/src/main/java/jp/co/soramitsu/feature_staking_impl/presentation/staking/controller/SetControllerViewModel.kt
> +        listenFee()
listenFee не особо тут имеет смысл, так как fee грузится только один раз)

2021-05-05 06:59 UTC, valentunn commented on feature-staking-impl/src/main/java/jp/co/soramitsu/feature_staking_impl/presentation/staking/controller/SetControllerViewModel.kt
> +        viewModelScope.launch { loadFee() }
А зачем запускать корутину? loadFee же не suspend

2021-05-05 06:59 UTC, valentunn commented on feature-staking-impl/src/main/java/jp/co/soramitsu/feature_staking_impl/presentation/staking/controller/SetControllerFragment.kt
> +        continueBtn.setOnClickListener { viewModel.continueClicked() }
`continueBtn` - я бы всё-таки предложил называть вбюшки как screen + viewName. Чтобы не запутаться в куче continueBtn с разных экранов)

2021-05-05 06:59 UTC, valentunn commented
Валидации отдельным ПР оформишь позже?

2021-05-05 07:00 UTC, valentunn commented
А так в целом - хорошая работа! Быстро разробралась

2021-05-05 07:39 UTC, FrogTravel commented on feature-staking-impl/src/main/java/jp/co/soramitsu/feature_staking_impl/presentation/staking/controller/SetControllerViewModel.kt
> +    private val _controllerAccountModel = MutableLiveData<AddressModel>()
Вооот. С этим вчера знатно зависла что-то. Сейчас еще потыкаю, если не разберусь свежим взглядом, напишу тебе

2021-05-05 07:40 UTC, FrogTravel commented
> Валидации отдельным ПР оформишь позже?

Похоже на такие комменты нельзя нормально реплай сделать. Да. Хотела ПР сделать, а то и так он жирненький уже вышел

2021-05-05 07:53 UTC, valentunn commented on feature-staking-impl/src/main/java/jp/co/soramitsu/feature_staking_impl/presentation/staking/controller/SetControllerViewModel.kt
> +    private val _controllerAccountModel = MutableLiveData<AddressModel>()
Мне кажется, тут надо в init блоке запутстить корутину, которая дождется первого значения из accountStakingFlow и запихнет adressModel из controllerAddress в лавйвдату

2021-05-05 08:35 UTC, FrogTravel commented on feature-staking-impl/src/main/java/jp/co/soramitsu/feature_staking_impl/presentation/staking/controller/SetControllerViewModel.kt
> +        listenFee()
Done

2021-05-05 08:35 UTC, FrogTravel commented on feature-staking-impl/src/main/java/jp/co/soramitsu/feature_staking_impl/presentation/staking/controller/SetControllerViewModel.kt
> +    private val _controllerAccountModel = MutableLiveData<AddressModel>()
Done
Как-то сделала, но хз. Кажется можно аккуратнее

2021-05-05 08:35 UTC, FrogTravel commented on feature-staking-impl/src/main/java/jp/co/soramitsu/feature_staking_impl/presentation/staking/controller/SetControllerViewModel.kt
> +    val showControllerChooserEvent: LiveData<Event<Payload<AddressModel>>> = _showControllerChooserEvent
Done

2021-05-05 08:35 UTC, FrogTravel commented on feature-staking-impl/src/main/java/jp/co/soramitsu/feature_staking_impl/presentation/staking/controller/SetControllerViewModel.kt
> +    override val openBrowserEvent = MutableLiveData<Event<String>>()
Done

2021-05-05 08:45 UTC, FrogTravel commented on feature-staking-impl/src/main/java/jp/co/soramitsu/feature_staking_impl/presentation/staking/controller/SetControllerFragment.kt
> +        continueBtn.setOnClickListener { viewModel.continueClicked() }
Done

2021-05-05 08:55 UTC, FrogTravel commented on feature-staking-impl/src/main/java/jp/co/soramitsu/feature_staking_impl/presentation/staking/controller/SetControllerViewModel.kt
> +        viewModelScope.launch { loadFee() }
Done

2021-05-05 09:29 UTC, valentunn commented on feature-staking-impl/src/main/java/jp/co/soramitsu/feature_staking_impl/presentation/staking/controller/ControllerChooserBottomSheetDialog.kt
> +    context, payload, AddressModelDiffCallback, clickHandler
Может лучше обобщить существующий компонент? Передавая title в конструктор. А то прям 1 в 1 код, за исключением одной строки

2021-05-05 09:29 UTC, valentunn commented on feature-staking-impl/src/main/java/jp/co/soramitsu/feature_staking_impl/presentation/staking/controller/SetControllerViewModel.kt
> +        }.asLiveData())
Мне кажется, что нам достаточно только первого значения из accountStakingFlow

2021-05-05 11:56 UTC, FrogTravel commented on feature-staking-impl/src/main/java/jp/co/soramitsu/feature_staking_impl/presentation/staking/controller/SetControllerViewModel.kt
> +        }.asLiveData())
Done

2021-05-05 11:57 UTC, FrogTravel commented on feature-staking-impl/src/main/java/jp/co/soramitsu/feature_staking_impl/presentation/staking/controller/ControllerChooserBottomSheetDialog.kt
> +    context, payload, AddressModelDiffCallback, clickHandler
Done

2021-05-05 12:39 UTC, valentunn commented on feature-staking-impl/src/main/java/jp/co/soramitsu/feature_staking_impl/presentation/staking/controller/SetControllerViewModel.kt
> +                        stackingInteractor.getAccount(it.controllerAddress).name
Увидел, что код, дублируется два раза в рамках экрана, мб вынести в отдельный метод?

2021-05-06 13:58 UTC, FrogTravel commented on feature-staking-impl/src/main/java/jp/co/soramitsu/feature_staking_impl/presentation/staking/controller/SetControllerViewModel.kt
> +                        stackingInteractor.getAccount(it.controllerAddress).name
Done

2021-05-06 14:28 UTC, valentunn approved these changes

2021-05-06 16:47 UTC, merged