fixes/roundings
soramitsu/fearless-Android pull request #889
Opened 2023-05-02 15:15 UTC by PankraSerg

2023-05-02 17:20 UTC, VitalyPeryatin requested changes

2023-05-02 17:20 UTC, VitalyPeryatin commented on common/src/main/java/jp/co/soramitsu/common/utils/NumberFormatters.kt
> +const val CRYPTO_DETAIL_PRECISION = 8
Let's name it like that: `MAX_DECIMALS_8`

2023-05-02 17:20 UTC, VitalyPeryatin commented on common/src/main/java/jp/co/soramitsu/common/utils/NumberFormatters.kt
>  private const val CRYPTO_LISTS_PRECISION = 3
Let's name it like that: `MAX_DECIMALS_3`

2023-05-03 05:04 UTC, Deneath submitted a review, later dismissed

2023-05-03 06:57 UTC, Deneath approved these changes

2023-05-03 07:11 UTC, VitalyPeryatin approved these changes

2023-05-03 07:12 UTC, merged