wip chain registry
soramitsu/fearless-Android pull request #895
Opened 2023-05-15 06:28 UTC by Deneath

2023-05-15 06:50 UTC, VitalyPeryatin requested changes

2023-05-15 06:50 UTC, VitalyPeryatin commented on feature-wallet-impl/src/main/java/jp/co/soramitsu/wallet/impl/di/WalletFeatureModule.kt
> +    @Singleton
`Singleton` redundant for `Interactor`

2023-05-15 06:50 UTC, VitalyPeryatin commented on feature-wallet-impl/src/main/java/jp/co/soramitsu/wallet/impl/domain/XcmInteractor.kt
> +    private val xcmService: MutableStateFlow<XcmService?> = MutableStateFlow(null)
We can move `xcmService` to `XcmRepository` to keep Interactor stateless

2023-05-15 06:50 UTC, VitalyPeryatin commented on feature-wallet-impl/src/main/java/jp/co/soramitsu/wallet/impl/domain/XcmInteractor.kt
> +    private suspend fun buildFromChainData(originChainId: ChainId): FromChainData {
We can move this logic to `XcmRepository`, but it seems too hard

2023-05-15 06:50 UTC, VitalyPeryatin commented on feature-wallet-impl/src/main/java/jp/co/soramitsu/wallet/impl/domain/XcmInteractor.kt
> +            val selfAddress = currentAccountAddress(originChain.id) ?: throw IllegalStateException("No self address")
`throw IllegalStateException` -> `error`

2023-05-15 06:50 UTC, VitalyPeryatin commented on feature-wallet-impl/src/main/java/jp/co/soramitsu/wallet/impl/domain/XcmInteractor.kt
> +        val r = runCatching {
`r`?

2023-05-15 06:50 UTC, VitalyPeryatin commented on feature-wallet-impl/src/main/java/jp/co/soramitsu/wallet/impl/domain/XcmInteractor.kt
> +        val r = runCatching {
`r`?

2023-05-18 07:12 UTC, PankraSerg approved these changes

2023-05-18 07:31 UTC, PankraSerg approved these changes

2023-05-18 07:41 UTC, VitalyPeryatin approved these changes

2023-05-18 07:41 UTC, VitalyPeryatin approved these changes

2023-05-18 07:51 UTC, merged